/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '副本': typeof import('./src/components/subfolder - 副本.vue')['default']
    AmazingFeaturesSection: typeof import('./src/components/AmazingFeaturesSection.vue')['default']
    AppBar: typeof import('./src/components/app/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/app/AppFooter.vue')['default']
    AwardWinningSection: typeof import('./src/components/AwardWinningSection.vue')['default']
    Bookmarkitem: typeof import('./src/components/bookmarkitem.vue')['default']
    Clear: typeof import('./src/components/clear.vue')['default']
    ContactUsSection: typeof import('./src/components/ContactUsSection.vue')['default']
    CustomizeSection: typeof import('./src/components/CustomizeSection.vue')['default']
    DiscoverHelp: typeof import('./src/components/DiscoverHelp.vue')['default']
    Email: typeof import('./src/components/email.vue')['default']
    Export: typeof import('./src/components/export.vue')['default']
    FAQSection: typeof import('./src/components/FAQSection.vue')['default']
    FunFactsSection: typeof import('./src/components/FunFactsSection.vue')['default']
    LandingSection: typeof import('./src/components/LandingSection.vue')['default']
    LogoSection: typeof import('./src/components/LogoSection.vue')['default']
    Logout: typeof import('./src/components/logout.vue')['default']
    MeetOurTeamSection: typeof import('./src/components/MeetOurTeamSection.vue')['default']
    OurPortfolioSection: typeof import('./src/components/OurPortfolioSection.vue')['default']
    PricingSection: typeof import('./src/components/PricingSection.vue')['default']
    Redirect: typeof import('./src/components/redirect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subfolder: typeof import('./src/components/subfolder.vue')['default']
    'Subfolder - 副本': typeof import('./src/components/subfolder - 副本.vue')['default']
    WhatPeopleSaySection: typeof import('./src/components/WhatPeopleSaySection.vue')['default']
    WhatWeDoSection: typeof import('./src/components/WhatWeDoSection.vue')['default']
  }
}
